# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :sensu_client1 do |client|
    client.vm.box = "centos/7"
    client.vm.network :private_network, ip: "192.168.56.101"
    #client.vm.network "public_network", bridge: "eth4", ip:"192.168.131.100", netmask: "255.255.255.0"
    client.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256","--cpus", "1", "--name", "sensu_client1" ]
    end
    client.vm.provision "shell", inline: <<-SHELL
      sudo yum install screen vim -y
      echo '[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
gpgcheck=0
enabled=1' | sudo tee /etc/yum.repos.d/sensu.repo
      yum install sensu -y
      sensu-install -p sensu-plugin
      yum install httpd -y
    SHELL
  end
  config.vm.define :sensu_server1 do |server|
    server.vm.box = "centos/7"
    server.vm.network :private_network, ip: "192.168.56.103"
    #server.vm.network "public_network", bridge: "eth4", ip:"192.168.131.101", netmask: "255.255.255.0"
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256","--cpus", "1", "--name", "sensu_server1" ]
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo yum install screen vim -y
      echo '[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
gpgcheck=0
enabled=1' | sudo tee /etc/yum.repos.d/sensu.repo
      yum install sensu -y
      sensu-install -p sensu-plugin
      sensu-install -p sensu-plugins-slack
      su -c 'rpm -Uvh http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm'
      yum install erlang -y
      yum install redis -y
      yum install socat -y
      su -c 'rpm -Uvh http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-3.6.9-1.el7.noarch.rpm'
      service rabbitmq-server start
      sudo rabbitmqctl add_vhost /sensu
      sudo rabbitmqctl add_user sensu password
      sudo rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"
      rabbitmq-plugins enable rabbitmq_management
      chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/
      rabbitmqctl add_user test test
      rabbitmqctl set_user_tags test administrator
      rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
    SHELL
  end
end

